name: pyenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - setuptools<65
  - gfortran_linux-64>=11.2.0   
  - openblas>=0.3.18          
  - ninja>=1.10.2
  - openmpi>=5.0.8
